// constants/sidebarItems.js

import {
  DashboardOutlined,
  SettingOutlined,
  LineChartOutlined,
  UsergroupAddOutlined,
  AppstoreOutlined,
  EnvironmentOutlined,
  CalendarOutlined,
  TransactionOutlined,
  UserAddOutlined,
  QuestionCircleOutlined,
  IoNotificationsOutline,
  SiTheconversation,
} from "@ant-design/icons";

export const menuItems = [
  {
    id: "dashboard",
    name: "Dashboard",
    path: "/",
    icon: <DashboardOutlined />,
    accessKey: "isDashboardShow",
  },
  {
    id: "analytics",
    name: "Analytics",
    path: "/analytics",
    icon: <LineChartOutlined />,
    accessKey: "isAnalyticsShow",
  },
  {
    id: "bookings",
    name: "Bookings",
    path: "/bookings",
    icon: <CalendarOutlined />,
    accessKey: "isBookingManagement",
  },
  {
    id: "transactions",
    name: "Transactions",
    path: "/transaction",
    icon: <TransactionOutlined />,
    accessKey: "isTransactionsShow",
  },
  {
    id: "services",
    name: "Services",
    path: "/services",
    icon: <AppstoreOutlined />,
    accessKey: "isServicesShow",
  },
  {
    id: "users",
    name: "Users",
    path: "/users",
    icon: <UsergroupAddOutlined />,
    accessKey: "isUsersShow",
  },
  {
    id: "managers",
    name: "Managers",
    path: "/manager-management",
    icon: <UserAddOutlined />,
    accessKey: "isManagerManagement",
  },
  {
    id: "states",
    name: "States",
    path: "/states",
    icon: <EnvironmentOutlined />,
    accessKey: "isState",
  },
  {
    id: "notifications",
    name: "Notifications",
    path: "/notification",
    icon: <IoNotificationsOutline />,
    accessKey: "isHelpAndSupport",
  },
  {
    id: "profile",
    name: "Profile",
    path: "/profile",
    icon: <UsergroupAddOutlined />,
    accessKey: "isProfileShow",
  },
  {
    id: "siteContent",
    name: "Site Content",
    path: "/site-content",
    icon: <SettingOutlined />,
    accessKey: "isSiteContentShow",
  },
  {
    id: "legalities",
    name: "Legalities",
    path: "/legalities",
    icon: <SiTheconversation />,
    accessKey: "isLegalitiesShow",
  },
  {
    id: "helpSupport",
    name: "Help & Support",
    path: "/help",
    icon: <QuestionCircleOutlined />,
    accessKey: "isHelpAndSupport",
  },
];
